version: '2'
services:
    videogenweb-app:
        image: videogenweb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://videogenweb-mysql:3306/videogenweb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    videogenweb-mysql:
        extends:
            file: mysql.yml
            service: videogenweb-mysql
